export const        
GET_POKEMONS = "GET_POKEMONS", 
GET_TYPES = "GET_TYPES", 
POST_POKEMON = "POST_POKEMON",
SET_ORDER = "SET_ORDER",
SET_ORDER_TYPE = "SET_ORDER_TYPE",
FILTER_BY_TYPE = "FILTER_BY_TYPE",
SET_ORDERED_POKEMONS = "SET_ORDERED_POKEMONS",
SET_PAGINATION = "SET_PAGINATION",
SET_PAGE = "SET_PAGE",
SET_ORIGIN = "SET_ORIGIN",
GET_POKEMON_NAME = "GET_POKEMON_NAME",
GET_POKEMON_ID = "GET_POKEMON_ID"
